// frontend/src/app/components/share/share-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ShareSettings, User } from '../../interfaces';

@Component({
  selector: 'app-share-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    @if (isOpen) {
      <div class="fixed inset-0 bg-gray-900/50 flex items-center justify-center z-50">
        <div class="bg-primary-bg p-6 rounded-lg w-full max-w-md">
          <h2 class="text-xl font-semibold text-text-primary mb-4">Share {{ itemType }}</h2>
          
          <div class="space-y-6">
            <!-- Share with Users -->
            <div>
              <h3 class="text-lg font-medium text-text-primary mb-2">Share with Users</h3>
              <div class="space-y-4">
                <div>
                  <input
                    type="text"
                    [(ngModel)]="userSearchQuery"
                    placeholder="Search users..."
                    class="w-full px-4 py-2 bg-secondary-bg text-text-primary rounded-lg border border-[var(--border-color)]"
                  />
                  @if (filteredUsers.length > 0) {
                    <div class="mt-2 bg-[var(--card-bg)] rounded-lg border border-[var(--border-color)] max-h-48 overflow-y-auto">
                      @for (user of filteredUsers; track user.id) {
                        <button
                          class="w-full px-4 py-2 flex items-center gap-3 hover:bg-secondary-bg"
                          (click)="selectUser(user)"
                        >
                          <div class="w-8 h-8 rounded-full bg-[var(--accent)] text-white flex items-center justify-center">
                            {{ user.name[0].toUpperCase() }}
                          </div>
                          <div class="text-left">
                            <p class="text-text-primary">{{ user.name }}</p>
                            <p class="text-sm text-text-secondary">{{ user.email }}</p>
                          </div>
                        </button>
                      }
                    </div>
                  }
                </div>

                @if (selectedUsers.length > 0) {
                  <div class="space-y-2">
                    @for (user of selectedUsers; track user.id) {
                      <div class="flex items-center justify-between p-2 bg-secondary-bg rounded-lg">
                        <div class="flex items-center gap-2">
                          <div class="w-8 h-8 rounded-full bg-[var(--accent)] text-white flex items-center justify-center">
                            {{ user.name[0].toUpperCase() }}
                          </div>
                          <span class="text-text-primary">{{ user.name }}</span>
                        </div>
                        <div class="flex items-center gap-2">
                          <select
                            [(ngModel)]="userPermissions[user.id]"
                            class="px-2 py-1 bg-[var(--card-bg)] rounded border border-[var(--border-color)]"
                          >
                            <option value="read">Read</option>
                            <option value="write">Write</option>
                          </select>
                          <button
                            class="p-1 text-red-500 hover:bg-red-500/10 rounded"
                            (click)="removeUser(user)"
                          >
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                          </button>
                        </div>
                      </div>
                    }
                  </div>
                }

                <label class="flex items-center gap-2">
                  <input
                    type="checkbox"
                    [(ngModel)]="shareSettings.notifyByEmail"
                    class="rounded border-[var(--border-color)]"
                  />
                  <span class="text-text-primary">Notify users by email</span>
                </label>
              </div>
            </div>

            <!-- Share via Link -->
            <div>
              <h3 class="text-lg font-medium text-text-primary mb-2">Share via Link</h3>
              <div class="space-y-4">
                @if (shareSettings.link) {
                  <div class="flex gap-2">
                    <input
                      type="text"
                      [value]="shareSettings.link"
                      readonly
                      class="flex-1 px-4 py-2 bg-secondary-bg text-text-primary rounded-lg border border-[var(--border-color)]"
                    />
                    <button class="btn-secondary" (click)="copyLink()">Copy</button>
                  </div>
                } @else {
                  <button class="btn-secondary w-full" (click)="generateLink()">Generate Link</button>
                }

                @if (shareSettings.link) {
                  <div class="space-y-2">
                    <div>
                      <label class="block text-sm font-medium text-text-secondary mb-1">Link Expiration</label>
                      <select
                        [(ngModel)]="linkExpiration"
                        class="w-full px-3 py-2 bg-secondary-bg rounded-lg border border-[var(--border-color)]"
                        (change)="updateLinkExpiration()"
                      >
                        <option value="never">Never</option>
                        <option value="1day">1 day</option>
                        <option value="7days">7 days</option>
                        <option value="30days">30 days</option>
                        <option value="custom">Custom date</option>
                      </select>
                    </div>

                    @if (linkExpiration === 'custom') {
                      <input
                        type="date"
                        [(ngModel)]="customExpirationDate"
                        class="w-full px-3 py-2 bg-secondary-bg rounded-lg border border-[var(--border-color)]"
                        (change)="updateLinkExpiration()"
                      />
                    }
                  </div>
                }
              </div>
            </div>
          </div>

          <div class="mt-6 flex justify-end gap-2">
            <button class="btn-secondary" (click)="close()">Cancel</button>
            <button class="btn-primary" (click)="share()">Share</button>
          </div>
        </div>
      </div>
    }
  `
})
export class ShareModalComponent {
  @Input() isOpen = false;
  @Input() itemType: 'file' | 'password' | 'group' = 'file';
  @Input() itemId = '';
  @Output() closeModal = new EventEmitter<void>();
  @Output() shareItem = new EventEmitter<ShareSettings>();

  userSearchQuery = '';
  linkExpiration: 'never' | '1day' | '7days' | '30days' | 'custom' = 'never';
  customExpirationDate = '';
  selectedUsers: User[] = [];
  userPermissions: Record<string, 'read' | 'write'> = {};

  shareSettings: ShareSettings = {
    id: '',
    fileId: '',
    type: 'private',
    notifyByEmail: false
  };

  // Mock users for demo
  users: User[] = [
    { id: '1', name: 'John Doe', email: 'john@example.com' },
    { id: '2', name: 'Jane Smith', email: 'jane@example.com' },
    { id: '3', name: 'Bob Johnson', email: 'bob@example.com' }
  ];

  get filteredUsers(): User[] {
    const query = this.userSearchQuery.toLowerCase();
    return this.users.filter(user => 
      !this.selectedUsers.includes(user) &&
      (user.name.toLowerCase().includes(query) || 
       user.email.toLowerCase().includes(query))
    );
  }

  selectUser(user: User): void {
    this.selectedUsers.push(user);
    this.userPermissions[user.id] = 'read';
    this.userSearchQuery = '';
  }

  removeUser(user: User): void {
    this.selectedUsers = this.selectedUsers.filter(u => u.id !== user.id);
    delete this.userPermissions[user.id];
  }

  generateLink(): void {
    this.shareSettings = {
      ...this.shareSettings,
      id: crypto.randomUUID(),
      fileId: this.itemId,
      type: 'public',
      link: `https://example.com/share/${crypto.randomUUID()}`
    };
  }

  copyLink(): void {
    if (this.shareSettings.link) {
      navigator.clipboard.writeText(this.shareSettings.link);
    }
  }

  updateLinkExpiration(): void {
    if (!this.shareSettings.link) return;

    let expiresAt: Date | undefined;
    
    switch (this.linkExpiration) {
      case '1day':
        expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000);
        break;
      case '7days':
        expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
        break;
      case '30days':
        expiresAt = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
        break;
      case 'custom':
        expiresAt = this.customExpirationDate ? new Date(this.customExpirationDate) : undefined;
        break;
      default:
        expiresAt = undefined;
    }

    this.shareSettings.expiresAt = expiresAt;
  }

  share(): void {
    const settings: ShareSettings = {
      ...this.shareSettings,
      allowedUsers: this.selectedUsers.map(user => user.id)
    };
    this.shareItem.emit(settings);
    this.close();
  }

  close(): void {
    this.resetForm();
    this.closeModal.emit();
  }

  private resetForm(): void {
    this.shareSettings = {
      id: '',
      fileId: '',
      type: 'private',
      notifyByEmail: false
    };
    this.selectedUsers = [];
    this.userPermissions = {};
    this.userSearchQuery = '';
    this.linkExpiration = 'never';
    this.customExpirationDate = '';
  }
}

// frontend/src/components/shared/ShareModal.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Item, User, ItemType } from '../../types';
import { useToast } from '../../context/ToastContext';
import { X, Users, Link2, Copy, Check, Search, Trash2 } from 'lucide-react';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  items: Item[];
  onShare?: (users: { userId: string; permissions: { read: boolean; write: boolean } }[]) => void;
}

const ShareModal: React.FC<ShareModalProps> = ({ isOpen, onClose, items, onShare }) => {
  const { showToast } = useToast();
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<User[]>([]);
  const [selectedUsers, setSelectedUsers] = useState<{
    userId: string;
    permissions: { read: boolean; write: boolean };
  }[]>([]);
  const [showSearchResults, setShowSearchResults] = useState(false);
  const [publicLink, setPublicLink] = useState<string | null>(null);
  const searchContainerRef = useRef<HTMLDivElement>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);

  // Initialize selected users from items' shared users
  useEffect(() => {
    if (items.length === 1 && items[0].sharedWith) {
      setSelectedUsers(
        items[0].sharedWith.map(share => ({
          userId: share.userId,
          permissions: share.permissions
        }))
      );
    }
  }, [items]);

  // Handle click outside search results
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        searchContainerRef.current &&
        !searchContainerRef.current.contains(event.target as Node)
      ) {
        setShowSearchResults(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Search users
  useEffect(() => {
    if (searchQuery.length > 0) {
      const mockUsers: any = [
        { _id: '1', name: 'Alice', surname: 'Smith', email: 'alice@example.com', avatar: '' },
        { _id: '2', name: 'Bob', surname: 'Johnson', email: 'bob@example.com', avatar: '' },
        { _id: '3', name: 'Charlie', surname: 'Brown', email: 'charlie@example.com', avatar: '' },
      ];
      const results = mockUsers.filter(
        (user: any) =>
          (user.name.toLowerCase() + ' ' + user.surname.toLowerCase()).includes(
            searchQuery.toLowerCase()
          ) ||
          user.email.toLowerCase().includes(searchQuery.toLowerCase())
      );
      setSearchResults(results); 
      setShowSearchResults(true);
    } else {
      setSearchResults([]);
      setShowSearchResults(false);
    }
  }, [searchQuery]);

  const handleUserSelect = (user: User) => {
    if (!selectedUsers.some(u => u.userId === user._id)) {
      setSelectedUsers([
        ...selectedUsers,
        { userId: user._id, permissions: { read: true, write: false } }
      ]);
    }
    setSearchQuery('');
    setShowSearchResults(false);
    if (searchInputRef.current) {
      searchInputRef.current.focus();
    }
  };

  const handlePermissionChange = (userId: string, type: 'read' | 'write', value: boolean) => {
    setSelectedUsers(prev =>
      prev.map(user =>
        user.userId === userId
          ? {
              ...user,
              permissions: {
                ...user.permissions,
                [type]: value,
                // Ensure read permission is enabled if write permission is enabled
                read: type === 'write' ? (value ? true : user.permissions.read) : value
              }
            }
          : user
      )
    );
  };

  const removeUser = (userId: string) => {
    setSelectedUsers(prev => prev.filter(user => user.userId !== userId));
    showToast('User removed from sharing');
  };

  const generatePublicLink = () => {
    // In a real app, this would make an API call to generate a unique link
    const link = `https://CloudMesa.example.com/share/${items[0]._id}`;
    setPublicLink(link);
    showToast('Public link generated');
  };

  const copyPublicLink = async () => {
    if (!publicLink) return;
    
    try {
      await navigator.clipboard.writeText(publicLink);
      showToast('Link copied to clipboard');
    } catch (error) {
      showToast('Failed to copy link', 'error');
    }
  };

  const handleShare = () => {
    if (onShare) {
      onShare(selectedUsers);
    }
    showToast('Sharing settings updated');
    onClose();
  };

  if (!isOpen) return null;
  const users = [
    { _id: '1', name: 'Alice', surname: 'Smith', email: 'alice@example.com', avatar: '' },
    { _id: '2', name: 'Bob', surname: 'Johnson', email: 'bob@example.com', avatar: '' },
    { _id: '3', name: 'Charlie', surname: 'Brown', email: 'charlie@example.com', avatar: '' },
  ];
  const getUserById = (id: string) => users.find(user => user._id === id);

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-elevation-3 w-full max-w-lg">
        <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center space-x-2">
            <Users className="h-5 w-5 text-primary-500" />
            <h2 className="text-lg font-semibold">
              Share {items.length > 1 ? `${items.length} items` : items[0].itemName}
            </h2>
          </div>
          <button
            onClick={onClose}
            className="p-1 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-full"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-4 space-y-4">
          {/* User search */}
          <div ref={searchContainerRef} className="relative">
            <div className="flex items-center bg-gray-100 dark:bg-gray-900 rounded-lg px-3 py-2">
              <Search className="h-5 w-5 text-gray-400" />
              <input
                ref={searchInputRef}
                type="text"
                placeholder="Add people by name or email"
                className="ml-2 bg-transparent border-none outline-none w-full"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>

            {/* Search results dropdown */}
            {showSearchResults && searchResults.length > 0 && (
              <div className="absolute z-10 mt-1 w-full bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 max-h-48 overflow-y-auto">
                {searchResults.map(user => (
                  <button
                    key={user._id}
                    className="w-full flex items-center px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700 text-left"
                    onClick={() => handleUserSelect(user)}
                  >
                    <div className="w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-900 flex items-center justify-center overflow-hidden">
                      {user.avatar ? (
                        <img src={user.avatar} alt={user.name} className="w-full h-full object-cover" />
                      ) : (
                        <span className="font-medium text-primary-700 dark:text-primary-300">
                          {user.name.charAt(0)}
                          {user.surname.charAt(0)}
                        </span>
                      )}
                    </div>
                    <div className="ml-3">
                      <div className="font-medium">{user.name} {user.surname}</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">{user.email}</div>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Selected users list */}
          {selectedUsers.length > 0 && (
            <div className="space-y-2">
              {selectedUsers.map(({ userId, permissions }) => {
                const user = getUserById(userId);
                if (!user) return null;

                return (
                  <div
                    key={userId}
                    className="flex items-center justify-between bg-gray-50 dark:bg-gray-900 rounded-lg p-3"
                  >
                    <div className="flex items-center">
                      <div className="w-8 h-8 rounded-full bg-primary-100 dark:bg-primary-900 flex items-center justify-center overflow-hidden">
                        {user.avatar ? (
                          <img src={user.avatar} alt={user.name} className="w-full h-full object-cover" />
                        ) : (
                          <span className="font-medium text-primary-700 dark:text-primary-300">
                            {user.name.charAt(0)}
                            {user.surname.charAt(0)}
                          </span>
                        )}
                      </div>
                      <div className="ml-3">
                        <div className="font-medium">{user.name} {user.surname}</div>
                        <div className="text-sm text-gray-500 dark:text-gray-400">{user.email}</div>
                      </div>
                    </div>

                    <div className="flex items-center space-x-3">
                      <div className="flex items-center space-x-2">
                        <label className="flex items-center space-x-1 text-sm">
                          <input
                            type="checkbox"
                            checked={permissions.read}
                            onChange={(e) => handlePermissionChange(userId, 'read', e.target.checked)}
                            className="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                          />
                          <span>Read</span>
                        </label>
                        <label className="flex items-center space-x-1 text-sm">
                          <input
                            type="checkbox"
                            checked={permissions.write}
                            onChange={(e) => handlePermissionChange(userId, 'write', e.target.checked)}
                            className="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                          />
                          <span>Write</span>
                        </label>
                      </div>
                      <button
                        onClick={() => removeUser(userId)}
                        className="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded"
                      >
                        <Trash2 className="h-4 w-4 text-gray-500" />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {/* Public link section (only for single file/folder) */}
          {items.length === 1 && items[0].type === ItemType.FILE && (
            <div className="mt-6 pt-4 border-t border-gray-200 dark:border-gray-700">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center space-x-2">
                  <Link2 className="h-5 w-5 text-gray-500" />
                  <span className="font-medium">Public Link</span>
                </div>
                {!publicLink && (
                  <button
                    onClick={generatePublicLink}
                    className="text-sm text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300"
                  >
                    Generate Link
                  </button>
                )}
              </div>

              {publicLink && (
                <div className="flex items-center space-x-2">
                  <input
                    type="text"
                    value={publicLink}
                    readOnly
                    className="flex-1 bg-gray-100 dark:bg-gray-900 rounded px-3 py-2 text-sm"
                  />
                  <button
                    onClick={copyPublicLink}
                    className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded"
                  >
                    <Copy className="h-4 w-4" />
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        <div className="flex justify-end gap-2 p-4 border-t border-gray-200 dark:border-gray-700">
          <button onClick={onClose} className="btn btn-secondary">
            Cancel
          </button>
          <button onClick={handleShare} className="btn btn-primary">
            Share
          </button>
        </div>
      </div>
    </div>
  );
};

export default ShareModal;
